mqtt:
  broker:
    host: localhost
    port: 1883
    username: ""
    password: ""

simulator:
  controller_name: Telescope
  topic_prefix: OnStepX
  commands:
    - command: ":GR#"
      response: "12:34:56#"
    - command: ":GD#"
      response: "+45*30:00#"

logging:
  debug_enabled: false
  max_total_size_mb: 100
